---
# Hands on data pipelines: automated X-Ray images analysis!
platform: babylon
purpose: demo

# ---------------------------------------------------------
# OCP configuration
# ---------------------------------------------------------

__meta__:
  deployer:
    scm_url: https://github.com/guimou/agnosticd.git
    scm_ref: guimou-xraydemo
    virtualenv: ansible2.9-python3.6-2021-01-22