---
purpose: rhtr2020-development

agnosticv_meta:
  idle_after_deploy: 2
  idle_after_start: 2

__meta__:
  deployer:
    scm_ref: rhtr-guimou
    scm_url: https://github.com/guimou/agnosticd.git

  secrets:
    # Sets target_host
    - name: rhtr-xray-data-pipelines-dev
      namespace: gpte
