---
# MERGED:
# xraylab/ALL-IN-ONE/common.yaml
# xraylab/ALL-IN-ONE/dev.yaml
__meta__:
  aws_sandboxed: true
  catalog:
    category: Labs
    display_name: Hands On Data Pipelines
    icon: openshift
    keywords:
    - lab
    - ocp4
    - openshift
    - openshift container storage
    - amq
    labels:
      Event: Red_Hat_Summit
      OpenShift_Version: "4.8"
      Product: OpenShift
      Provider: GPTE
  deployer:
    scm_ref: development
    scm_url: https://github.com/redhat-cop/agnosticd.git
    virtualenv: ansible2.9-python3.6-2021-01-22
  secrets:
  - name: ocp4-token
    namespace: gpte
  - name: ipa-admin
    namespace: gpte
  - name: satellite-rhel81
    namespace: gpte
cloud_provider: none
env_type: ocp-workloads
ocp_workloads:
- ocp4_workload_serverless
- ocp4_workload_bookbag_setup
- ocp4_workload_xray_pipeline_lab
ocp4_workload_amq_streams_channel: stable
ocp4_workload_amq_streams_starting_csv: amqstreams.v1.8.3
ocp4_workload_amq_streams_use_catalog_snapshot: false
ocp4_workload_amq_streams_wait_for_deploy: true
ocp4_workload_bookbag_setup_git_repo: https://github.com/red-hat-data-services/xraylab-bookbag.git
ocp4_workload_bookbag_setup_git_version: main
ocp4_workload_bookbag_setup_image_name: xraylab-bookbag
ocp4_workload_bookbag_setup_project: bookbag
ocp4_workload_bookbag_setup_project_display: Bookbag XRay Lab
ocp4_workload_serverless_channel: stable
ocp4_workload_serverless_install_eventing: true
ocp4_workload_serverless_use_catalog_snapshot: false
ocp4_workload_xray_pipeline_lab_install_kafkasource: true
ocp4_workload_xray_pipeline_lab_install_odh: true
ocp4_workload_xray_pipeline_lab_install_odh_operator: true
ocp4_workload_xray_pipeline_lab_odh_automatic_install_plan_approval: true
ocp4_workload_xray_pipeline_lab_odh_channel: stable
ocp4_workload_xray_pipeline_lab_odh_operator_name: opendatahub-operator
ocp4_workload_xray_pipeline_lab_use_catalogsource_setup: false
ocp4_workload_xray_pipeline_lab_user_base: xraylab-
ocp4_workload_xray_pipeline_lab_user_count: 10
platform: babylon
purpose: demo
