---
# ---------------------------------------------------------
# AgnosticV Metadata
# ---------------------------------------------------------
agnosticv_meta:
  idle_after_deploy: 9999
  idle_after_start: 9999

__meta__:
  deployer:
    scm_url: https://github.com/redhat-cop/agnosticd
    scm_ref: development
