---
# Red Hat RHTR 2020 - Hands on data pipelines: automated X-Ray images analysis!
platform: labs
purpose: rhtr2020-development   ## This is a cost tag, please make sure it's correct.

# ---------------------------------------------------------
# OCP configuration
# ---------------------------------------------------------
master_instance_type: c5d.2xlarge
master_instance_count: 3
worker_instance_type: m5.4xlarge
worker_instance_count: 3

# ---------------------------------------------------------
# AgnosticV Metadata
# ---------------------------------------------------------
agnosticv_meta:
  idle_after_deploy: 9999
  idle_after_start: 9999

__meta__:
  deployer:
    scm_url: https://github.com/redhat-cop/agnosticd
    scm_ref: development
