---
# /common.yaml
# /xraylab/account.yaml
# /xraylab/BASE/common.yaml
# /xraylab/BASE/dev.yaml
key_name: opentlc_admin_backdoor
output_dir: ./configs/{{ env_type }}-{{ guid }}
own_repo_path: http://d3s3zqyaz8cp2d.cloudfront.net/repos/ocp/{{osrelease}}
owner: gpte-devops-automation@redhat.com
email: gpte-devops-automation@redhat.com
platform: opentlc
cloud_tags:
  env_type: "{{ env_type }}"
  guid: "{{ guid }}"
  course_name: "{{ course_name | default(course_id) | default('unknown') }}"
  platform: "{{ platform | default('unknown') }}"
  purpose: "{{ purpose | default('unknown') }}"
  uuid: "{{ uuid | default('unknown') }}"
agnosticv_meta:
  babylon:
    # This file lives in ~/secrets on the deploy host
    kubeconfig: babylon-prod.kubeconfig
  # Instead of running ansible-playbook from the admin host,
  # tell ALL_agnosticv.sh to use babylon to deploy.
  deploy_with: babylon
  # Use a specific virtualenv that has all the k8s modules
  virtualenv: babylon
  # Pass through guid to use in ResourceClaim name
  params_to_variables:
    guid: guid
    user: ocp_username
  idle_after_deploy: 9999
  idle_after_start: 9999
__meta__:
  catalog:
    namespace: rhtr
    tags:
      - babylon
    description: >-
      Hands on data pipelines: automated X-Ray images analysis!
  deployer:
    scm_url: https://github.com/redhat-cop/agnosticd
    scm_type: git
    type: agnosticd
    scm_ref: development
  # Enable GPTE reporting to the Provisions DB, for cost management
  secrets:
    # Enable GPTE reporting to the Provisions DB, for cost management
    - name: gpte-db
      namespace: gpte
      var: gpte_db
  tower:
    organization: gpte
cloud_provider: none
env_type: ocp-workloads
ocp_workloads:
  - ocp4_workload_serverless
  - ocp4_workload_rhtr_xraylab
  - ocp4_workload_bookbag_setup
ocp4_workload_serverless_channel: "4.5"
ocp4_workload_serverless_install_eventing: true
ocp4_workload_serverless_use_catalog_snapshot: true
ocp4_workload_serverless_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_serverless_catalog_snapshot_image_tag: v4.5_2020_10_01
ocp4_workload_serverless_starting_csv: "serverless-operator.v1.9.0"
ocp4_workload_rhtr_xraylab_install_storage: true
ocp4_workload_rhtr_xraylab_install_amqstreams_operator: true
ocp4_workload_rhtr_xraylab_install_odh_operator: true
ocp4_workload_rhtr_xraylab_install_kafkasource: true
ocp4_workload_rhtr_xraylab_use_catalog_snapshot: true
ocp4_workload_rhtr_xraylab_catalogsources:
  - name: redhat-operators-snapshot-xraylab
    namespace: openshift-marketplace
    image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
    tag: "v4.5_2020_10_01"
  - name: community-operators-snapshot-xraylab
    namespace: openshift-marketplace
    image: quay.io/gpte-devops-automation/olm_snapshot_community_catalog
    tag: "v4.5_2020_10_01"
ocp4_workload_rhtr_xraylab_ocs_expected_crds:
  - backingstores.noobaa.io
  - bucketclasses.noobaa.io
  - noobaas.noobaa.io
  - objectbucketclaims.objectbucket.io
ocp4_workload_rhtr_xraylab_ocs_channel: stable-4.5
ocp4_workload_rhtr_xraylab_ocs_install_mcg: false
ocp4_workload_rhtr_xraylab_ocs_install_rgw: true
ocp4_workload_rhtr_xraylab_ocs_mcg_core_cpu: 1
ocp4_workload_rhtr_xraylab_ocs_mcg_core_mem: 4Gi
ocp4_workload_rhtr_xraylab_ocs_mcg_db_cpu: 1
ocp4_workload_rhtr_xraylab_ocs_mcg_db_mem: 4Gi
ocp4_workload_rhtr_xraylab_ocs_ceph_mds_cpu: 3
ocp4_workload_rhtr_xraylab_ocs_ceph_mds_mem: 8Gi
ocp4_workload_rhtr_xraylab_ocs_ceph_mon_cpu: 1
ocp4_workload_rhtr_xraylab_ocs_ceph_mon_mem: 2Gi
ocp4_workload_rhtr_xraylab_ocs_ceph_mgr_cpu: 1
ocp4_workload_rhtr_xraylab_ocs_ceph_mgr_mem: 3Gi
ocp4_workload_rhtr_xraylab_ocs_ceph_osd_cpu: 2
ocp4_workload_rhtr_xraylab_ocs_ceph_osd_mem: 5Gi
ocp4_workload_rhtr_xraylab_ocs_ceph_storage_class_name: gp2
ocp4_workload_rhtr_xraylab_ocs_ceph_storage_osd_size: 2Ti
ocp4_workload_rhtr_xraylab_ocs_mcg_pv_pool: false
ocp4_workload_rhtr_xraylab_ocs_mcg_pv_pool_bucket_name: mcg
ocp4_workload_rhtr_xraylab_ocs_mcg_pv_pool_pv_size: 50Gi
ocp4_workload_rhtr_xraylab_ocs_mcg_pv_pool_pv_quantity: 3
ocp4_workload_rhtr_xraylab_ocs_mcg_pv_pool_pv_storageclass: gp2
ocp4_workload_rhtr_xraylab_ocs_namespace: openshift-storage
ocp4_workload_rhtr_xraylab_ocs_release: v4.5.0
ocp4_workload_rhtr_xraylab_ocs_operator_workload_destroy: "{{ False if (ACTION=='create' or ACTION=='provision') else True }}"
ocp4_workload_rhtr_xraylab_kafkasource: "v0.17.2"
ocp4_workload_bookbag_setup_project: "bookbag"
ocp4_workload_bookbag_setup_project_display: "Bookbag RHTR2020 XRay Lab"
ocp4_workload_bookbag_setup_git_repo: https://github.com/guimou/rhtr2020_xraylab.git
ocp4_workload_bookbag_setup_git_version: main
ocp4_workload_bookbag_setup_image_name: rhtr2020xraylabbookbag
